- pyproject.toml
- src/capymoa/evaluation/visualization.py
- add `plot_regression_results` method
- add `plot_prediction_interval_results` method
- modify `plot_windowed_results` function to have an option to `prevent_plotting_drift`
> feat: add plot_regression/prediction_interval_results functions

- src/capymoa/base.py
- src/capymoa/classifier/__init__.py
- src/capymoa/classifier/_dynamic_weighted_majority.py
- src/capymoa/classifier/_hoeffding_adaptive_tree.py
- src/capymoa/classifier/_samknn.py
- tests/test_classifiers.py
Add wrappers for:
- Hoeffding Adaptive Tree (HAT)
- Dynamic Weighted Majority (DWM)
- Self Adjusted Memory k Nearest Neighbours (SAMkNN)
Update `__init__` to allow import
Add tests to `test_classifiers.py`
> feat: add HAT, DWM, and SAMkNN wrappers

- src/capymoa/base.py
- src/capymoa/evaluation/visualization.py
Update plotting functions for regression results and prediction interval.
minor: add `setContextForModel()` to MOARegressor in `base.py`
> feat: update plotting regression/prediction interval

- src/capymoa/evaluation/evaluation.py
Remove redundant and useless code in PI Evaluator
> fix: remove useless code in PI evaluator

- notebooks/anomaly_detection.ipynb
- notebooks/index.rst
- src/capymoa/anomaly/__init__.py
- src/capymoa/anomaly/half_space_trees.py
- src/capymoa/evaluation/__init__.py
- src/capymoa/evaluation/evaluation.py
- tests/test_anomaly_detectors.py
Add wrapper for Half-Space Trees for MOA.
> feat(Anomaly-Detection): add Half-Space Trees

- invoke.yml
- src/capymoa/anomaly/half_space_trees.py
- tests/test_moajar.py
Updating MOA jar to reflect bug fix in HSTreeNode random object
> fix: updating moa jar 24-05-20

- src/capymoa/datasets/__init__.py
- src/capymoa/datasets/_datasets.py
- src/capymoa/datasets/_source_list.py
add the `Bike` dataset for documentation and future use.
> refactor(datasets): add Bike dataset into _datasets.py

- src/capymoa/classifier/__init__.py
- src/capymoa/classifier/_csmote.py
- tests/test_classifiers.py
CSMOTE classifier designed to cope with imbalanced data within streaming environments. The algorithm implementation is based on the work by Alessio Bernardo et al. [C-SMOTE: Continuous Synthetic Minority Oversampling for Evolving Data Streams](https://ieeexplore.ieee.org/document/9377768). In BigData, IEEE, 2020.
> feat(CSMOTE): adding CSMOTE for imbalanced learning

- src/capymoa/regressor/__init__.py
- src/capymoa/regressor/_fimtdd.py
- src/capymoa/regressor/_knn.py
- src/capymoa/regressor/_orto.py
- src/capymoa/regressor/_passive_aggressive_regressor.py
- src/capymoa/regressor/_sgd_regressor.py
- src/capymoa/regressor/_soknl.py
- src/capymoa/regressor/_soknl_base_tree.py
-- Add documenting for regressors:
```FIMTDD```
```ORTO```
```KNNRegressor```
```Passive Aggressive Regressor```
```SGD Regressor```
```SOKNL```
```SOKNLBT```
-- Update `__init__.py` accordingly
> docs: adding documentation for regressors

- src/capymoa/classifier/__init__.py
- src/capymoa/classifier/_leveraging_bagging.py
- src/capymoa/classifier/_online_adwin_bagging.py
- tests/test_classifiers.py
Added LeveragingBagging
Added OnlineAdwinBagging
Modified __init__ to include both
> feat: adding LeveragingBagging and OnlineAdwinBagging classes

- notebooks/save_and_load_model.ipynb
Small update to the notebook added by #131 demonstrating the save and load capabilities in capymoa
> fix: updating save_load notebook

- tasks.py
Workaround for issue in jpype: https://github.com/jpype-project/jpype/issues/1194
> build: ignore the stub build issue in editable installs

- src/capymoa/base.py
- src/capymoa/classifier/_adaptive_random_forest.py
We can create more PRs to have this functionality applied to other learners
> Feat: Edited ADF algorithm to include CapyMoa Drift Detection Classes in its parameters

- invoke.yml
- tests/test_moajar.py
Update the MOA jar to include the latest additions to MOA, including experimental APIs, such as the AutoML one.
> chore: updating moa jar 24-09-08

- src/capymoa/classifier/_csmote.py
Simple update to C-SMOTE documentation. Addresses #189
> docs: update csmote init doc

- docs/_templates/autosummary/module.rst
- docs/conf.py
- pyproject.toml
- src/capymoa/datasets/_datasets.py
- src/capymoa/datasets/downloader.py
- src/capymoa/evaluation/_progress_bar.py
- src/capymoa/evaluation/evaluation.py
- tests/test_datasets.py
- tests/test_progress_bar.py
Currently this only works for un-optimised loops.
> feat: add optional progress bars

- invoke.yml
- src/capymoa/classifier/_srp.py
- tests/test_moajar.py
Updated the SRP wrapper to have the mini-batch functionality.
Updated the `invoke.yml` and `test_moajar.py` to include new moa.jar with the `SRP_MB`'s bug fixed.
Meanwhile, corrected the documentation for `num_features` parameter.
> feat: update srp with minibatch function

- CITATION.cff
updating `CITATION.cff` for correct citation information in Github repository.
> fix: updating .cff file for correct citation information

- docs/api/index.rst
- tasks.py
* `clusterers` and `automl` were missing from the api reference
> docs(api): add missing packages to api docs

- notebooks/drift_detection.ipynb
- src/capymoa/drift/base_detector.py
- src/capymoa/drift/detectors/__init__.py
- src/capymoa/drift/detectors/hddm_w.py
- src/capymoa/drift/detectors/studd.py
- src/capymoa/drift/eval_detector.py
PR contains:
- Significant changes in the evaluation of drift detectors
- New drift detector (STUDD)
- Fixed HDDM issue
- Updated drift detection notebook
> Drift detector evaluation v1 + STUDD + fix HDDM

- src/capymoa/evaluation/visualization.py
See https://github.com/orgs/adaptive-machine-learning/projects/2/views/5?pane=issue&itemId=83302586&issue=adaptive-machine-learning%7Cbacklog%7C3
> fix: bug with NaN values for plots

- src/capymoa/regressor/__init__.py
Fixing regression `__init__` formatting
> fix: init format
